// TimTomTimothysDineDash/SPAService/ClientApp/src/app/host/add-to-wait-queue/add-to-wait-queue.component.ts
import { Component, OnDestroy, OnInit } from '@angular/core';
import { HostStaffApiService } from '../host-staff-api.service';
import { HostStaffStatus } from '../data/host-staff-status';
import { NgForm } from '@angular/forms';
import { MessageService, OverlayService } from 'primeng/api';
import { TimsOverlayService } from 'src/app/shared/tims-overlay.service';

@Component({
  selector: 'app-add-to-wait-queue',
  templateUrl: './add-to-wait-queue.component.html',
  styleUrls: ['./add-to-wait-queue.component.scss'],
})
export class AddToWaitQueueComponent implements OnInit {
  isLoading = false;
  numOfCustomers: number = 1;

  constructor(private apiService: HostStaffApiService, private overlayService: TimsOverlayService) { }

  ngOnInit(): void {
  }


  async submit(f: NgForm): Promise<void> {
    this.isLoading = true;

    if (this.numOfCustomers < 1 || this.numOfCustomers > 6) return;

    let result = await this.apiService.insertPartyIntoQueue(this.numOfCustomers);

    if (result) { // It failed
      this.overlayService.addSingleToast('Failed', result, 'error');
    } else { // No message in result is indicative of success
      this.overlayService.addSingleToast('Success', 'The customer group has been added to the wait queue', 'success');
    }
    

    this.isLoading = false;
  }

  
}

<form #addToQueueForm="ngForm" (ngSubmit)="submit(addToQueueForm)">
    <div class="card">
        <div class="card-header text-center fw-bold">Add a Group to the Wait Queue</div>
        <div class="card-body">
            <label for="numOfCustomers" class="my-2">How many customers are in this group?</label>
            <p-slider [(ngModel)]="numOfCustomers" id="numOfCustomers" name="numOfCustomers" [min]="1" [max]="6"></p-slider>
            <div class="row">
                <div class="col-2 py-3" *ngFor="let item of [].constructor(numOfCustomers); let indexOfElement = index">
                    <i class="bi bi-person-fill fs-4"></i> {{indexOfElement + 1}}
                </div>
            </div>
        </div>
        <div class="card-footer row">
            <div class="col-4"></div>
            <div class="col-4 text-center">
                <button class="btn btn-primary m-100" type="submit" *ngIf="!isLoading">Add Party</button>
                <p-progressSpinner *ngIf="isLoading"></p-progressSpinner>
            </div>
            <div class="col-4"></div>
        </div>
    </div>
</form>

// TimTomTimothysDineDash/ReactSPAService/client-app/src/routes/host-page/add-to-wait-queue/add-to-wait-queue.component.jsx
import { useState, Fragment } from "react";
import { ProgressSpinner } from 'primereact/progressspinner';
import { Slider } from 'primereact/slider';
import { insertPartyIntoQueue } from "../../../utils/api-handlers/api-host-page-handlers.util";

const AddToWaitQueue = ({toastHandler}) => {
    const [isLoading, setIsLoading] = useState(false);
    const [numOfCustomers, setNumOfCustomers] = useState(1); // One customer by default

    const handleSubmit = async (e) => {
        e.preventDefault();
        setIsLoading(true);

        if (numOfCustomers < 1 || numOfCustomers > 6) return;

        let result = await insertPartyIntoQueue(numOfCustomers);
        
        if (result) { // It failed
            toastHandler('error', 'Failed', result);
        } else { // No message in result is indicative of success
            toastHandler('success', 'Success', 'The customer group has been added to the wait queue');
            setNumOfCustomers(1);
        }
        
        
        setIsLoading(false);
    }

    const buildNumSelectedIndicator = () => {
      const numSelectedSlots = [];

      for (let j = 1; j <= numOfCustomers; j++) {
        numSelectedSlots.push(<div className="col-2 py-3" key={`Item ${j}`}><i className="bi bi-person-fill fs-4"></i> {j}</div>);
      }

      return numSelectedSlots;
    }

  return (
    <form onSubmit={handleSubmit}>
        <div className="card">
            <div className="card-header text-center fw-bold">Add a Group to the Wait Queue</div>
            <div className="card-body">
                <label htmlFor="numOfCustomers" className="my-2">How many customers are in this group?</label>
                <Slider value={numOfCustomers} onChange={(e) => setNumOfCustomers(e.value)} step={1} min={1} max={6} />
                <div className="row">
                    {buildNumSelectedIndicator()}
                </div>
            </div>
            <div className="card-footer row">
                <div className="col-4"></div>
                <div className="col-4 text-center">
                    {isLoading 
                        ?
                        <ProgressSpinner />
                        :
                        <button className="btn btn-primary m-100" type="submit">Add Party</button>
                    }
                </div>
                <div className="col-4"></div>
            </div>
        </div>
    </form>
  );
}

export default AddToWaitQueue;
