// TimTomTimothysDineDash/ReactSPAService/client-app/src/components/quick-access-menu/quick-access-menu.component.jsx
import './quick-access-menu.styles.scss';

import { Link } from 'react-router-dom';
import { Button } from 'primereact/button';

const QuickAccessMenu = () => {
    return (
        <div className="card my-3 quick-access-menu">
            <div className="card-body">
                <h5 className="card-title">Quick Access Menu</h5>
                <h6 className="card-subtitle">Press any Button to jump to the related page</h6>
                <div className="row mt-2">
                    <div className="col-lg-3 col-6">
                        Host Staff:
                        <hr/>
                        <Link to='/Host'><Button  type="Button" label="Main Page" severity='help' className="my-1 w-100"></Button></Link>
                        <Link to='/Host/AddToWaitQueue'><Button  type="Button" label="Add to Wait Queue" severity='help' className=" my-1 w-100"></Button></Link>
                        <Link to='/Host/SeatATable'><Button  type="Button" label="Seat a Table" severity='help' className=" my-1 w-100"></Button></Link>
                    </div>
                    <div className="col-lg-3 col-6">
                        Wait Staff:
                        <hr/>
                        <Link to='/Wait'><Button  type="Button" label="Main Page" severity='help' className=" my-1 w-100"></Button></Link>
                        <Link to='/Wait/InsertTakenOrder'><Button  type="Button" severity='help' label="Take Table's Order" className=" my-1 w-100"></Button></Link>
                        <Link to='/Wait/MarkOrderPaid'><Button  type="Button" severity='help' label="Mark Table as Paid" className=" my-1 w-100"></Button></Link>
                    </div>
                    <div className="col-lg-3 col-6">
                        Kitchen Staff:
                        <hr/>
                        <Link to='/Kitchen'><Button  type="Button" label="Main Page" severity='help' className=" my-1 w-100"></Button></Link>
                        <Link to='/Kitchen/StartCookingOrder'><Button  type="Button" severity='help' label="Start on Order" className=" my-1 w-100"></Button></Link>
                        <Link to='/Kitchen/MarkOrderFinished'><Button  type="Button" severity='help' label="Mark Order as Finished" className=" my-1 w-100"></Button></Link>
                    </div>
                    <div className="col-lg-3 col-6">
                        Bus Staff:
                        <hr/>
                        <Link to='/Bus'><Button  type="Button" label="Main Page" severity='help' className=" my-1 w-100"></Button></Link>
                        <Link to='/Bus/MarkTableAsCleaned'><Button  type="Button" severity='help' label="Mark Table as Cleaned" className=" my-1 w-100"></Button></Link>
                    </div>
                </div>
            </div>
        </div>
    );
}

export default QuickAccessMenu;

// TimTomTimothysDineDash/SPAService/ClientApp/src/app/shared/quick-access-menu/quick-access-menu.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'qam',
  templateUrl: './quick-access-menu.component.html',
  styleUrls: ['./quick-access-menu.component.scss']
})
export class QuickAccessMenuComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="card my-3 core-card">
    <div class="card-body">
        <h5 class="card-title">Quick Access Menu</h5>
        <h6 class="card-subtitle">Press any button to jump to the related page</h6>
        <div class="row mt-2">
            <div class="col-lg-3 col-6">
                Host Staff:
                <hr>
                <a [routerLink]="['/Host']"><button pButton type="button" label="Main Page" class="p-button-help my-1 w-100"></button></a>
                <a [routerLink]="['/Host/AddToWaitQueue']"><button pButton type="button" label="Add to Wait Queue" class="p-button-help my-1 w-100"></button></a>
                <a [routerLink]="['/Host/SeatATable']"><button pButton type="button" label="Seat a Table" class="p-button-help my-1 w-100"></button></a>
            </div>
            <div class="col-lg-3 col-6">
                Wait Staff:
                <hr>
                <a [routerLink]="['/Wait']"><button pButton type="button" label="Main Page" class="p-button-help my-1 w-100"></button></a>
                <a [routerLink]="['/Wait/InsertTakenOrder']"><button pButton type="button" label="Take Table's Order" class="p-button-help my-1 w-100"></button></a>
                <a [routerLink]="['/Wait/MarkOrderPaid']"><button pButton type="button" label="Mark Table as Paid" class="p-button-help my-1 w-100"></button></a>
            </div>
            <div class="col-lg-3 col-6">
                Kitchen Staff:
                <hr>
                <a [routerLink]="['/Kitchen']"><button pButton type="button" label="Main Page" class="p-button-help my-1 w-100"></button></a>
                <a [routerLink]="['/Kitchen/StartCookingOrder']"><button pButton type="button" label="Start on Order" class="p-button-help my-1 w-100"></button></a>
                <a [routerLink]="['/Kitchen/MarkOrderFinished']"><button pButton type="button" label="Mark Order as Finished" class="p-button-help my-1"></button></a>
            </div>
            <div class="col-lg-3 col-6">
                Bus Staff:
                <hr>
                <a [routerLink]="['/Bus']"><button pButton type="button" label="Main Page" class="p-button-help my-1 w-100"></button></a>
                <a [routerLink]="['/Bus/MarkTableAsCleaned']"><button pButton type="button" label="Mark Table as Cleaned" class="p-button-help my-1 w-100"></button></a>
            </div>
        </div>
    </div>
</div>
